[tool.poetry]
name = "yadt"
version = "0.0.1"
description = ""
authors = ["Pedro Sousa Lacerda <pslacerda@gmail.com>"]
packages = [{include = "yadt"}]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.scripts]
yadt-cli = "yadt.yadt_cli:cli"